name: Mi Aplicacion Stitch
on:
  push:
    branches: [ "principal" ]

jobs:
  construir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del codigo
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Validar archivos de Stitch
        run: echo "Preparando archivos..."

      # Este paso es el que fallaba, ahora con v4:
      - name: Subir resultado
        uses: actions/upload-artifact@v4
        with:
          name: Mi_App_Stitch
          path: .
